### ISSUE TITLE
socket.io

### ISSUE THREAD

**Issue by 4ware** [benawad/feathersjs-menu-monkey-backend#4]
Hi!

I was just playing with the new code but when i exchange the rest adapter for a socket.io one the authentication state is not persisted over page reloads anymore.

Do you have any idea why?

Thanks, Kai

**Comment by benawad** [comment]
Are you authenticating using sockets now?

**Comment by 4ware** [comment]
Er, yes . I think so. I just exchanged the client code for with .configure(socketio(socket))... Which reminds me that i should have asked in the issues for the client repo :(

**Comment by benawad** [comment]
No worries. When you switch to the socketio configuration, you will want to use sockets like at the bottom of this guide: https://docs.feathersjs.com/api/socketio.html 

You can also use both socketio and REST. But you need to create 2 different feathers objects (one configured with socketio and the other configured with REST).

**Comment by 4ware** [comment]
Ah, i see. Thanks a lot!
